### PR TITLE
feature: utilize the Noogle dataset for a rtfm command

### PR DESCRIPTION
**Pull request by itslychee**
work in progress

### CODE REVIEW

**Comment by viperML** [comment]
can we build the noogle data on github CI or the runner dies?. EDIT: seems to take 17minutes but at least it doesn't die

**Comment by itslychee** [comment]
>  seems to take 17minutes but at least it doesn't die

ouch..., perhaps I should instead include a copy of the built data

**Comment by viperML** [comment]
I mean, I'd say it is OK for CI. Perhaps good to have pre-built data for dev but it's not big deal if you find it hard to automate.

**Comment by viperML** [comment]
gave up? 😄

**Pull request closed without merging**
