### PR TITLE
Rework $move, add $resources, and add devShell 

### PR DESCRIPTION
**Pull request by itslychee**
image
image
image
image
image
image
image
image

### CODE REVIEW

**Comment by itslychee** [comment]
@viperML I reverted it back to nixpkgs instead of poetry2nix, let me know if there's anything else that must be done.

**Comment by viperML** [comment]
In the end how do you manage the jishaku dependency, or what is it needed for?

**Comment by itslychee** [comment]
I removed it, it was for evals and reloading extensions without needing to restart the bot.

**Comment by viperML** [comment]
Please revert the changes to the default.nix, flake.nix and .envrc too

**Comment by itslychee** [comment]
why?

**Comment by viperML** [comment]
The devshell is not needed (just nix develop .#packages.${system}.name)

**Comment by itslychee** [comment]
Oh cool! Very curious on how that works? does it just check if it has an `env` attribute and if so it uses that?

**Comment by itslychee** [comment]
Okay fixed, I updated the top line of `.envrc` to be `use flake .#package`

**Comment by viperML** [comment]
> Oh cool! Very curious on how that works? does it just check if it has an `env` attribute and if so it uses that?

It's the other way around, `nix develop` / `nix-shell` provide the build environment of a derivation. mkShell or the .env of python.withPackages are simplified derivations

**Comment by adamcstephens** [comment]
is this ready to go?

**Comment by itslychee** [comment]
> provide the build environment of a deri

Ah! Thanks

**Comment by itslychee** [comment]
> is this ready to go?

Looks like the bot is now running with this PR!

**Pull request merged**
